# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a48b8e1ee70907ce06e996ced63d3ff3a020d4ac34f84fbfa24d6842c73bb4dc6910993a1a607274070f22b6945527822895be04bdab41a86707383955b9d44

test:
  secret_key_base: 00b015992c32e3b95021d3a77f9b24af1f07db482d0ce6f1d1dfa83da30d571cbab7dcbb147a870cadf1420e6f009d4ef0dfdeca8dd041aa61fd57b7253ab135

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
