# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8b4ab41787f99abd962c3a3df4fbe302e36cb9f10f0d993f446c2b79fca6b11b87e5a92e328a30f271589c0f0f0a20d3c38e66806a7785ac56a5ad0a3848f25

test:
  secret_key_base: e79a0213d438d241c5d793a7a0ec5bfbe6317a45d46817578a80e3ca30b48a0dca024107014f632be2165f177afdf107d852ad0cf0192d07866b4a047c41c2fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
